name: deploy

on:
  push:
    branches:
      - hiui

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        # 选择要使用的 node 版本
        node-version: '14'

      - name: Install
      run: npm install


      - name: Build
        run: |
          npm run build

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2
        with:
          publish_dir: ./dist
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          user_name: ${{ secrets.USER_NAME }}
          user_email: ${{ secrets.USER_EMAIL }}
          force_orphan: true
          commit_message: deploy gh-pages
